### ISSUE TITLE
Todo: Als Tab in yrewrite umsetzen

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/url_scheme#1]

**Comment by tbaddade** [comment]
> Als Tab in yrewrite umsetzen

Finde ich nicht gut. Nur AddOns sollten ihre eigenen PlugIns mitbringen. "Installer Updates"

**Comment by gharlan** [comment]
> Finde ich nicht gut. Nur AddOns sollten ihre eigenen PlugIns mitbringen. "Installer Updates"

Wie schon an anderer Stelle angemerkt, bin ich hier klar anderer Meinung. Ich finde es legitim, wenn sich Addons als Subpage bei anderen Addons einbinden, und deswegen habe ich es in R5 auch so gebaut, dass es sehr einfach möglich ist (wenn das Mutteraddon die Subpages "korrekt" einbindet).

Ich finde, dieses Addon ist ein Paradebeispiel dafür, wo es Sinn ergibt. Sehe da null Vorteile drin (im Gegenteil), wenn das Addon stattdessen eine eigene Haupt-Page erstellen würde.

**Comment by skerbis** [comment]
Also, ein anderes Addon sollte kein Tab in einem anderen AddOn haben? Auch nicht wenn es darauf aufbaut? Ich empfinde es eigentlich als sinnlos für jede kleine Einstellung einen Hauptmenüpunkt zu verbrauchen. Das hier meinte ich
<img width="745" alt="bildschirmfoto 2017-10-09 um 20 27 30" src="https://user-images.githubusercontent.com/791247/31352838-851b377a-ad30-11e7-8f5e-f99382ac2570.png">

**Comment by skerbis** [comment]
Ich bitte um Klärung im Core-Team. Wäre echt schade, wenn Ihr was dagegen hättet.

**Comment by gharlan** [comment]
> Wie schon an anderer Stelle angemerkt

Hier meinte ich diese Diskussion: https://github.com/redaxo/redaxo/issues/1042

**Comment by tbaddade** [comment]
> Sehe da null Vorteile drin (im Gegenteil), wenn das Addon stattdessen eine eigene Haupt-Page erstellen würde.

Verstehe gar nicht warum als Extra-AddOn. Warum nicht als PR im YRewrite Addon anbieten?

**Comment by skerbis** [comment]
Ich sehe es aktuell noch nicht für gut genug an. Wenn https://github.com/FriendsOfREDAXO/url_scheme/issues/3 umgesetzt ist vielleicht.

**Comment by gharlan** [comment]
> Verstehe gar nicht warum als Extra-AddOn. Warum nicht als PR im YRewrite Addon anbieten?

Das ist eine Frage, die sich ja immer wieder stellt, und wie ich finde, nicht so leicht zu beantworten ist.

Da müsste ja erstmal auch geklärt werden, ob wir das überhaupt direkt in YRewrite drin haben wollen.
Über das Theme habe ich mit Jan im Laufe der Jahre immer mal wieder diskutiert, ob wir YRewrite eher so clean wie möglich halten wollen, und es somit für speziellere Wünsche bei der programmatischen Lösung (eigene Scheme-Klasse) bleiben soll, oder ob wir eher weitere Optionen hinzufügen wollen, sodass möglichst viele sich ihre individuellen Vorstellungen für das Schema zusammen klicken können. Und wenn ja, wie weit man da geht.
So richtig entschieden waren wir da nie.

Aber abseits dieser Frage, gibt es auch so Vor- und Nachteile.
Nachteil der Variante "eigenes Addon" ist klar: Ein weiteres Addon. Was man so mitkriegt, stört das schon einige, wie viele Addons man inzwischen meist so "braucht".
Vorteile allerdings gibt es auch: Man ist völlig frei von den Yakamara-Entscheidungen, die FOR-Community könnte hier eigenständig diverse Optionen sammeln, die uns in YRewrite vielleicht eher zu viel wären, oder zu instabil, oder sonstwas.
YRewrite würde so "clean" bleiben, und wer sich gerne individueller das Schema zusammen klicken möchte, müsste sich halt das Zusatzaddon installieren.

Ich bin hier offen für beide Wege, kann beiden was abgewinnen.

**Comment by skerbis** [comment]
Ich bin auch eher für die Clean-Variante. Wer die URL-Schemes aus diesem AddOn nicht haben will, kann eine andere Lösung verwenden. (aktuell ist mir eine weitere bekannt). Aber es gibt eben Sonderfälle die ein Konfigurator oder Selektor nicht abdeckt. Es sollte offen bleiben. Ich möchte nun nur geklärt wissen ob ich mich mit einem Tab einklinken kann/darf oder nicht. Sonst muss grundsätzlich über ein Bereich nachgedacht werden wo kleine Settings untergebracht werden.

**Comment by skerbis** [comment]
@tbaddade @gharlan  Gegenvorschlag um es sichtbar als externes AddOn zu machen:
<img width="771" alt="bildschirmfoto 2017-10-09 um 21 26 43" src="https://user-images.githubusercontent.com/791247/31354969-b4986a92-ad38-11e7-9ccd-3a47d3bbd976.png">

**Comment by skerbis** [comment]
In https://github.com/redaxo/redaxo/issues/1042 hatte ich auch meine Bedenken, aber irgendwie leuchtet es mir hier auch nicht mehr ein, einen eigen Menüpunkt dafür zu haben.

**Comment by gharlan** [comment]
> Ich möchte nun nur geklärt wissen ob ich mich mit einem Tab einklinken kann/darf oder nicht.

Es gibt im Core-Team da Dissens, der sich wohl nicht auflösen lässt. 
Aber so oder so: Es ist möglich, und keiner kann es verbieten. Es ist somit eine FOR-Entscheidung, ob das Addon sich als Subpage einhaken soll. Ich stimme klar dafür.
Wie das nun genau gestaltet ist (Screenshot 1 oder 2) ist mir egal.

**Comment by skerbis** [comment]
ok. Danke für's Feedback

**Comment by schuer** [comment]
Was Gregor sagt. Und Screenshot 1.
